### ISSUE TITLE
Customize memory form footer needs improvement.

### ISSUE THREAD

**Issue by 7H3XXX** [addyosmani/chatty#53]
I think a little improvement can be here, on the screenshot, when the screen size gets narrower (less than 400px) the layout becomes inconsistent.
![image](https://github.com/addyosmani/chatty/assets/49251439/c866077b-1271-4bfe-ab89-a15bec274c81)

I think this can be a better way to do it.
![image_2024-06-12_02-32-04](https://github.com/addyosmani/chatty/assets/49251439/d22bd54e-379f-48d8-94e3-78736c249752)

If you think too I already made a fix locally, I will just create a PR so it can be merged after approval.

**Comment by jakobhoeg** [comment]
Go ahead and create a PR with the changes :)
