### ISSUE TITLE
[feature request]: system sync theme

### ISSUE THREAD

**Issue by maifeeulasad** [addyosmani/chatty#57]
Right now, we have these two following themes:
 - light
 - dark

Let's add one more, called `system sync` (and let's make it default maybe?!!)

Eager to work on this, so feel free to assign this to me.

**Comment by maifeeulasad** [comment]
Current themes:

![image](https://github.com/addyosmani/chatty/assets/29339330/576dccc6-18d5-42a5-90c2-fffe72758fe6)

**Comment by jakobhoeg** [comment]
> Right now, we have these two following themes:
> 
> * light
> * dark
> 
> Let's add one more, called `system sync` (and let's make it default maybe?!!)
> 
> Eager to work on this, so feel free to assign this to me.

Good ide! Go ahead and implement it :)

**Comment by maifeeulasad** [comment]
Thanks @jakobhoeg 

I have raised a PR, please check 😃
