### ISSUE TITLE
failed to load model: No URL found for model ID "Text-based model". Please check if the model ID is correct and included in the model_list configuration.

### ISSUE THREAD

**Issue by maifeeulasad** [addyosmani/chatty#58]
every time I send a query, I get this same response back: `failed to load model: No URL found for model ID "Text-based model". Please check if the model ID is correct and included in the model_list configuration.`. I have tried different models.

related snap:

![image](https://github.com/addyosmani/chatty/assets/29339330/c9178133-bdcb-4cac-8921-504163b7bbff)

**Comment by jakobhoeg** [comment]
I think this was an recent issue with Huggingface. Should work now. If not, try clearing the site data
